steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.prebuilt', '-t', 'gcr.io/${PROJECT_ID}/klipstream-analysis', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/klipstream-analysis']
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
