steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.fast', '-t', 'us-central1-docker.pkg.dev/klipstream/cloud-run-source-deploy/klipstream-analysis:fix', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/klipstream/cloud-run-source-deploy/klipstream-analysis:fix']
images:
- 'us-central1-docker.pkg.dev/klipstream/cloud-run-source-deploy/klipstream-analysis:fix'
options:
  machineType: 'E2_HIGHCPU_8'
timeout: '1200s'
